version: '3'

services:
  vault:
    container_name: vault
    ports:
      - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8100
    cap_add:
      - "IPC_LOCK"
